### PR TITLE
Enhancement: Replace String Representations with Date Objects for Career Timeline 

### LINKED ISSUE #289: feat(ericbuettner/career-timeline): implement Date Objects for Start- & End Dates of Job Positions
**Background:**

Currently, the "ericbuettner/career-timeline" library uses string representations for start and end dates of job positions. This approach can lead to potential issues, such as incorrect date formatting, difficulties in sorting, and limited date manipulation capabilities. To enhance the project's functionality and data consistency, it would be beneficial to replace these string representations with Date objects.

**Task:**

- Replace string-based representations of start and end dates with Date objects throughout the codebase.
- Ensure that the date parsing and formatting functions are robust and handle various date formats gracefully.

**Acceptance Criteria:**

Start and end dates are stored and manipulated as Date objects, not strings/enums.
The codebase is thoroughly tested to validate that the changes do not introduce any regressions.
The project's documentation is updated to include instructions for developers on how to work with Date objects for job positions.

**Additional Information:**

Please ensure that this change adheres to best practices for maintainability. Be mindful of backward compatibility if necessary and thoroughly test the code to ensure it functions as expected.

### PR DESCRIPTION
**Pull request by Manoj0Marmat**
## Description

This PR addresses the issue of using string representations for start and end dates in the "ericbuettner/career-timeline" library. It replaces string-based representations with Date objects throughout the codebase to enhance functionality and data consistency.

## Changes Made

- Replaced string-based representations of start and end dates with Date objects.
- Ensured robust date parsing and formatting functions to handle various date formats gracefully.

## Additional Info

This change adheres to best practices for maintainability and considers backward compatibility.

## Related Issues

[Closes #289]

### CODE REVIEW

**Comment by tuffz** [comment]
Thanks for your contribution, can you try running `npx nx format`, this should fix the linting warnings in 99% of cases.

**Comment by Manoj0Marmat** [comment]
> Thanks for your contribution, can you try running `npx nx format`, this should fix the linting warnings in 99% of cases.

yes done 👍 Thank you for your assistance.

**Comment by tuffz** [comment]
Hi @Manoj0Marmat,

finally I have found some time to look at the changes, but they do not exactly match my expectations, probably the ticket description was not precise enough on my part, for that I apologize.

Your changes have changed the presentation a bit, which should not be the case.

**How it looked before and how it should remain:**

Screenshot 2024-01-07 at 21 37 43

**How it looks like after your adjustment:**
Screenshot 2024-01-07 at 21 38 43

Unfortunately, I haven't gotten around to building a Jest test for this component yet, otherwise I would have noticed it sooner.

Sorry for the inconvenience.

**Comment by Manoj0Marmat** [comment]
Hey @tuffz can you let me know which url I should visit after the local application starts to view that component

**Comment by tuffz** [comment]
Sure, I have already adapted the README accordingly today.

After you have executed "nx serve ericbuettner-com" you should be able to reach the page via @http://localhost:4200.

**Comment by tuffz** [comment]
@Manoj0Marmat Thank you very much for your contribution. 🚀

**Pull request merged**
